FROM python:3.10

ENV PYTHONBUFFERED=1

WORKDIR /django_password_generator

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

CMD gunicorn password_generator.wsgi:application --bind 0.0.0.0:8000

EXPOSE 8000

